feat: alway execute renovate config validation
**WHY**
This workflow contains required status checks and therefore always must report back a status

**WHAT**
Always run the workflow. If no renovate config changes are detcted the matrix build gets skipped and the collector job reports back success.

diff --git a/.github/workflows/validate-renovate-config.yml b/.github/workflows/validate-renovate-config.yml
--- a/.github/workflows/validate-renovate-config.yml
+++ b/.github/workflows/validate-renovate-config.yml
@@ -4,10 +4,6 @@ on:
   push:
     branches-ignore:
       - main
-    paths:
-      - renovate.json
-      - default.json
-      - renovate-presets/**
 
 jobs:
   detect-modified-renovate-configs:
@@ -32,11 +28,11 @@ jobs:
     name: Validate Renovate Configs
     runs-on: ubuntu-latest
     needs: [detect-modified-renovate-configs]
+    if: ${{ needs.detect-modified-renovate-configs.outputs.matrix != '[]' }}
     strategy:
       matrix: 
         config: ${{ fromJSON(needs.detect-modified-renovate-configs.outputs.matrix) }}
       max-parallel: 4
-      fail-fast: false
     steps:
       - name: Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
@@ -53,12 +49,23 @@ jobs:
         run: renovate-config-validator ${{ matrix.config }}
 
   collect-validation-results:
+    # This job must always run and report a status since it is a required status check
     name: Renovate validation results collector
-    needs: [validate-renovate-configs]
+    needs: 
+        - detect-modified-renovate-configs
+        - validate-renovate-configs
     runs-on: ubuntu-latest
-    if: success()
+    if: always() && !cancelled()
     steps:
       - name: All renovate config validation jobs passed
         id: renovate-validation-passed
-        run: echo "All renovate config validation jobs passed!"
+        run: |
+          if [ "${{ needs.detect-modified-renovate-configs.outputs.matrix }}" == "[]" ]; then
+            echo "No renovate configuration changed"
+          elif [ "${{ needs.validate-renovate-configs.result }}" == "success" ]; then
+            echo "All renovate config validation jobs passed!"
+          else
+            echo "Renovate config validation failed!"
+            exit 1
+          fi
 
